/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SupportTerms_and_conditionsIndexRouteImport } from './routes/support/terms_and_conditions/index'
import { Route as SupportPrivacy_policyIndexRouteImport } from './routes/support/privacy_policy/index'
import { Route as AuthSign_upIndexRouteImport } from './routes/auth/sign_up/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthenticatedUserProfileIndexRouteImport } from './routes/_authenticated/user/profile/index'
import { Route as AuthenticatedUserMoodTrackerIndexRouteImport } from './routes/_authenticated/user/mood-tracker/index'
import { Route as AuthenticatedUserJournalIndexRouteImport } from './routes/_authenticated/user/journal/index'
import { Route as AuthenticatedUserDashboardIndexRouteImport } from './routes/_authenticated/user/dashboard/index'
import { Route as AuthenticatedUserChange_passwordIndexRouteImport } from './routes/_authenticated/user/change_password/index'
import { Route as AuthenticatedUserJournalJournal_detailRouteImport } from './routes/_authenticated/user/journal/$journal_detail'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTerms_and_conditionsIndexRoute =
  SupportTerms_and_conditionsIndexRouteImport.update({
    id: '/support/terms_and_conditions/',
    path: '/support/terms_and_conditions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SupportPrivacy_policyIndexRoute =
  SupportPrivacy_policyIndexRouteImport.update({
    id: '/support/privacy_policy/',
    path: '/support/privacy_policy/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSign_upIndexRoute = AuthSign_upIndexRouteImport.update({
  id: '/auth/sign_up/',
  path: '/auth/sign_up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserProfileIndexRoute =
  AuthenticatedUserProfileIndexRouteImport.update({
    id: '/user/profile/',
    path: '/user/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserMoodTrackerIndexRoute =
  AuthenticatedUserMoodTrackerIndexRouteImport.update({
    id: '/user/mood-tracker/',
    path: '/user/mood-tracker/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserJournalIndexRoute =
  AuthenticatedUserJournalIndexRouteImport.update({
    id: '/user/journal/',
    path: '/user/journal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserDashboardIndexRoute =
  AuthenticatedUserDashboardIndexRouteImport.update({
    id: '/user/dashboard/',
    path: '/user/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserChange_passwordIndexRoute =
  AuthenticatedUserChange_passwordIndexRouteImport.update({
    id: '/user/change_password/',
    path: '/user/change_password/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserJournalJournal_detailRoute =
  AuthenticatedUserJournalJournal_detailRouteImport.update({
    id: '/user/journal/$journal_detail',
    path: '/user/journal/$journal_detail',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/sign_up': typeof AuthSign_upIndexRoute
  '/support/privacy_policy': typeof SupportPrivacy_policyIndexRoute
  '/support/terms_and_conditions': typeof SupportTerms_and_conditionsIndexRoute
  '/user/journal/$journal_detail': typeof AuthenticatedUserJournalJournal_detailRoute
  '/user/change_password': typeof AuthenticatedUserChange_passwordIndexRoute
  '/user/dashboard': typeof AuthenticatedUserDashboardIndexRoute
  '/user/journal': typeof AuthenticatedUserJournalIndexRoute
  '/user/mood-tracker': typeof AuthenticatedUserMoodTrackerIndexRoute
  '/user/profile': typeof AuthenticatedUserProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/sign_up': typeof AuthSign_upIndexRoute
  '/support/privacy_policy': typeof SupportPrivacy_policyIndexRoute
  '/support/terms_and_conditions': typeof SupportTerms_and_conditionsIndexRoute
  '/user/journal/$journal_detail': typeof AuthenticatedUserJournalJournal_detailRoute
  '/user/change_password': typeof AuthenticatedUserChange_passwordIndexRoute
  '/user/dashboard': typeof AuthenticatedUserDashboardIndexRoute
  '/user/journal': typeof AuthenticatedUserJournalIndexRoute
  '/user/mood-tracker': typeof AuthenticatedUserMoodTrackerIndexRoute
  '/user/profile': typeof AuthenticatedUserProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/sign_up/': typeof AuthSign_upIndexRoute
  '/support/privacy_policy/': typeof SupportPrivacy_policyIndexRoute
  '/support/terms_and_conditions/': typeof SupportTerms_and_conditionsIndexRoute
  '/_authenticated/user/journal/$journal_detail': typeof AuthenticatedUserJournalJournal_detailRoute
  '/_authenticated/user/change_password/': typeof AuthenticatedUserChange_passwordIndexRoute
  '/_authenticated/user/dashboard/': typeof AuthenticatedUserDashboardIndexRoute
  '/_authenticated/user/journal/': typeof AuthenticatedUserJournalIndexRoute
  '/_authenticated/user/mood-tracker/': typeof AuthenticatedUserMoodTrackerIndexRoute
  '/_authenticated/user/profile/': typeof AuthenticatedUserProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth/login'
    | '/auth/sign_up'
    | '/support/privacy_policy'
    | '/support/terms_and_conditions'
    | '/user/journal/$journal_detail'
    | '/user/change_password'
    | '/user/dashboard'
    | '/user/journal'
    | '/user/mood-tracker'
    | '/user/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/auth/login'
    | '/auth/sign_up'
    | '/support/privacy_policy'
    | '/support/terms_and_conditions'
    | '/user/journal/$journal_detail'
    | '/user/change_password'
    | '/user/dashboard'
    | '/user/journal'
    | '/user/mood-tracker'
    | '/user/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/settings/'
    | '/auth/login/'
    | '/auth/sign_up/'
    | '/support/privacy_policy/'
    | '/support/terms_and_conditions/'
    | '/_authenticated/user/journal/$journal_detail'
    | '/_authenticated/user/change_password/'
    | '/_authenticated/user/dashboard/'
    | '/_authenticated/user/journal/'
    | '/_authenticated/user/mood-tracker/'
    | '/_authenticated/user/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSign_upIndexRoute: typeof AuthSign_upIndexRoute
  SupportPrivacy_policyIndexRoute: typeof SupportPrivacy_policyIndexRoute
  SupportTerms_and_conditionsIndexRoute: typeof SupportTerms_and_conditionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/terms_and_conditions/': {
      id: '/support/terms_and_conditions/'
      path: '/support/terms_and_conditions'
      fullPath: '/support/terms_and_conditions'
      preLoaderRoute: typeof SupportTerms_and_conditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/privacy_policy/': {
      id: '/support/privacy_policy/'
      path: '/support/privacy_policy'
      fullPath: '/support/privacy_policy'
      preLoaderRoute: typeof SupportPrivacy_policyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign_up/': {
      id: '/auth/sign_up/'
      path: '/auth/sign_up'
      fullPath: '/auth/sign_up'
      preLoaderRoute: typeof AuthSign_upIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user/profile/': {
      id: '/_authenticated/user/profile/'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof AuthenticatedUserProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/mood-tracker/': {
      id: '/_authenticated/user/mood-tracker/'
      path: '/user/mood-tracker'
      fullPath: '/user/mood-tracker'
      preLoaderRoute: typeof AuthenticatedUserMoodTrackerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/journal/': {
      id: '/_authenticated/user/journal/'
      path: '/user/journal'
      fullPath: '/user/journal'
      preLoaderRoute: typeof AuthenticatedUserJournalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/dashboard/': {
      id: '/_authenticated/user/dashboard/'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof AuthenticatedUserDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/change_password/': {
      id: '/_authenticated/user/change_password/'
      path: '/user/change_password'
      fullPath: '/user/change_password'
      preLoaderRoute: typeof AuthenticatedUserChange_passwordIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/journal/$journal_detail': {
      id: '/_authenticated/user/journal/$journal_detail'
      path: '/user/journal/$journal_detail'
      fullPath: '/user/journal/$journal_detail'
      preLoaderRoute: typeof AuthenticatedUserJournalJournal_detailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedUserJournalJournal_detailRoute: typeof AuthenticatedUserJournalJournal_detailRoute
  AuthenticatedUserChange_passwordIndexRoute: typeof AuthenticatedUserChange_passwordIndexRoute
  AuthenticatedUserDashboardIndexRoute: typeof AuthenticatedUserDashboardIndexRoute
  AuthenticatedUserJournalIndexRoute: typeof AuthenticatedUserJournalIndexRoute
  AuthenticatedUserMoodTrackerIndexRoute: typeof AuthenticatedUserMoodTrackerIndexRoute
  AuthenticatedUserProfileIndexRoute: typeof AuthenticatedUserProfileIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUserJournalJournal_detailRoute:
    AuthenticatedUserJournalJournal_detailRoute,
  AuthenticatedUserChange_passwordIndexRoute:
    AuthenticatedUserChange_passwordIndexRoute,
  AuthenticatedUserDashboardIndexRoute: AuthenticatedUserDashboardIndexRoute,
  AuthenticatedUserJournalIndexRoute: AuthenticatedUserJournalIndexRoute,
  AuthenticatedUserMoodTrackerIndexRoute:
    AuthenticatedUserMoodTrackerIndexRoute,
  AuthenticatedUserProfileIndexRoute: AuthenticatedUserProfileIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSign_upIndexRoute: AuthSign_upIndexRoute,
  SupportPrivacy_policyIndexRoute: SupportPrivacy_policyIndexRoute,
  SupportTerms_and_conditionsIndexRoute: SupportTerms_and_conditionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
